### ISSUE TITLE
Stocaudio plugins?

### ISSUE THREAD

**Issue by sramsay** [aptrn/stocaudio-modules#10]
Have you stopped maintaining your commercial plugins?  The website is down, Lock (at least) does not work with the latest version of Catalina . . .

**Comment by jocphx** [comment]
From looking at archive.org, the posts on facebook, and the dates on the code here on Github, all development activity ceased around Oct. 2019

**Comment by aptrn** [comment]
hi, i did take this up a copule of months ago, would love having a focused developing mindset again someday
https://zombie.stocaudio.com/

**Comment by jocphx** [comment]
Thank you, Alessandro, and best of luck with your endeavors! I hope you'll get your "mojo" back soon.

Per Aspera ad Astra

**Comment by sramsay** [comment]
Yes, Alessandro.  So nice to hear about your "mindset."  Trouble is, you were selling commercial products to people who had a reasonable expectation that you wouldn't completely disappear off the face of the earth without any notice whatsoever.

It seems to me that you are not ready -- personally or professionally -- to be in the business of selling and supporting commercial software products.  That's a shame; I think your stuff is really good.  But I won't be purchasing software from you in the future, and I strongly recommend that others do not as well.
