### ISSUE TITLE
polyDelay crashing

### ISSUE THREAD

**Issue by firolightfog** [aptrn/stocaudio-modules#18]
I was feeding the Basal VCO with a polyphonic signal and I tried to link its output to the polyDelay. Unfortunately it is crashing in my VCV Rack Free v.2.0.3 under Windows.

<img width="180" alt="image" src="https://user-images.githubusercontent.com/34127628/149676302-2cabcaaf-6815-4b97-b5da-57952b50bce2.png">

**Comment by aptrn** [comment]
Ye, already fixed, see #17 #16
Will push it next weekend i hope, checking other bugs as well 😄

**Comment by nesdnuma** [comment]
Hello, do you plan to push the module soon? It's been three weeks since your last message...

**Comment by aptrn** [comment]
i'm sorry, pushed now :)

**Comment by nesdnuma** [comment]
Thanks!
