### ISSUE TITLE
Controls not rendering on linux.

### ISSUE THREAD

**Issue by ContemporaryInsanity** [aptrn/stocaudio-modules#2]
![image](https://user-images.githubusercontent.com/12547379/65829659-8f197b00-e29f-11e9-8432-e4ef035bb909.png)

**Comment by spectromas** [comment]
Go to ~/.Rack/plugins-v1/stocaudio/res/ and rename 'comp' to Comp. Simple case typo.

**Comment by ContemporaryInsanity** [comment]
Thank you!

**Comment by spectromas** [comment]
No worries. You should probably keep this issue open, it is a bug which needs to be fixed.

**Comment by aptrn** [comment]
Ouch, didn't spot that on windows.
Fixed in plugin.hpp as "comp", if you pull you can rename the folder to lowercase.
