### ISSUE TITLE
Still no controls.

### ISSUE THREAD

**Issue by therealkitman** [aptrn/stocaudio-modules#4]
Hi.
Just downloaded your modules today via the plugin manager. The 'missing' panel knobs as reported in #3 still occurs. I renamed to the **C**omp folder and it works.
Did the fix from the closed issue not make it's way into the linux versions?
Thanks,
Chris.

**Comment by aptrn** [comment]
last commit is still not in the plugin manager, will be there soon!

**Comment by therealkitman** [comment]
Ah, ok. Thank you.
