### ISSUE TITLE
FR : Delay stereo shift

### ISSUE THREAD

**Issue by Petervos2018** [aptrn/stocaudio-modules#5]
Hi Allessandro,

love the whole set, and they look gorgeous.

Now for the FR, is it possible for the Delay to change the left and the right times, without connecting a cv to one/both of the left right attenuverters.
What I mean is, you can shift the left and right channels with the attenuverters, but only when there is a cv connected to them, and I want to change it without having to connect a cv.

Greetings Peter

**Comment by aptrn** [comment]
Yes, that would be nice, sure thing

Added on c4b74a940f48243910d9a92aefb01215dc0ec6f2

**Comment by Petervos2018** [comment]
Thanks !
