### ISSUE TITLE
does poly delay accept polyphonic delay time CV?

### ISSUE THREAD

**Issue by glocke01** [aptrn/stocaudio-modules#6]
Hi,

Thanks for all the cool modules!

I was hoping to try something using polydelay shepherd tone-style modulation applied to delay to produce a sort of wonky pitch shifter, but afaict polydelay is not interpreting polyphonic CV into delay time as polyphonic.

https://patchstorage.com/poly-delay-poly-cv-time/

**Comment by glocke01** [comment]
evidently the dude's name was Shepard and not Shepherd.

**Comment by aptrn** [comment]
Yeah, it should have been so already.
Now it's up! (on the plugin manager in a few days)
